spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb?useTimezone=true&serverTimezone=UTC
    username: sa
    password: 
  jpa:
    show-sql: false   